import Head from "next/head";
import { PostCard, Categories, PostWidget } from "../components/index";
// import styles from "../styles/Home.module.css";

const posts = [
  { title: "React-testing", excerpt: "Learn react testing" },
  { title: "React", excerpt: "Learn react basics" },
  { title: "react-tailwind", excerpt: "Learn react with tailwind" },
];

export default function Home() {
  return (
    <div className="container mx-auto px-10 mb-8">
      <Head>
        <title>Tech Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid grid-cols-2 lg:grid-cols-12 gap-12">
        <div className="lg:col-span-8 col-span-1">
          {posts.map((post) => (
            <PostCard key={post.title} post={post} />
          ))}
        </div>

        <div className="lg:col-span-4 col-span-1">
          <div className="lg:sticky relative top-8">
            <PostWidget />
            <Categories />
          </div>
        </div>
      </div>
    </div>
  );
}
